### ISSUE TITLE
0805 alternative 

### ISSUE THREAD

**Issue by kPATm** [Team-Resurgent/Modxo#11]
I cant source the 0805 diode here in the UK without paying crazy money for shipping. Is the a more easily available alternative part?

**Comment by AR1972** [comment]
you can probably get a SOD-323 diode too fit, the KYOCERA AVX SD0805S020S1R0 is what I got for a carrier board I made, kinda over kill and $0.35 each.

**Comment by shalxmva** [comment]
Just look for rectifier diodes, the idea is to use Silicon diodes with voltage drop of .7 or more

**Comment by kPATm** [comment]
Thanks. Any chance of a link on Ali to the correct ones the volume of components is overwhelming and TBH I dont really know what Im looking for

**Comment by shalxmva** [comment]
https://es.aliexpress.com/item/1005004629412368.html?spm=a2g0o.productlist.main.29.77f7js4Fjs4FPi&algo_pvid=b1feefb0-a1f9-43b3-aad4-8301b17e9435&algo_exp_id=b1feefb0-a1f9-43b3-aad4-8301b17e9435-14&pdp_npi=4%40dis%21MXN%2127.91%2127.91%21%21%219.82%219.82%21%40210318c317261794819591982e469b%2112000029896571474%21sea%21MX%211675221654%21X&curPageLogUid=bLiqSrBRzpBc&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by kPATm** [comment]
Thanks. I actually ordered these a few days ago. Not sure if they will work though?

IN4148 (without the W) SOD 323

**Comment by shalxmva** [comment]
I will keep this open, so you can post if that works for you

**Comment by kPATm** [comment]
Yes they seem to work fine
