### ISSUE TITLE
Wiring diagram for zero

### ISSUE THREAD

**Issue by bondsan-github** [Team-Resurgent/Modxo#4]
Pico wiring diagram has been updated but not the zero,
do the pico changes apply the same to the zero?

7 - RST (GP7) to LPC header pin 5
8 - LPC 3.3 (GP8) to LPC header pin 9 (1.6 only)

changes in purple.

![modxo zero version 1 0](https://github.com/user-attachments/assets/b6184758-cc6d-4101-a382-73062356f9bc)

**Comment by shalxmva** [comment]
For now is the same, but i am rearranging the pinout so it can handle more functionalities. So LAD pins wont be on the same place, but if no new functionalities are require, the Official pico image could still be used.

**Comment by bondsan-github** [comment]
Is the reset; RST (GP7) to LPC header pin 5 required using the 1.0 software?

**Comment by shalxmva** [comment]
Zero diagram already added.

**Comment by bondsan-github** [comment]
Nice diagram :) What software do you use? I use gimp beta.

**Comment by shalxmva** [comment]
photoshop, but going to drop my license because is too expensive. So i hope to start learning gimp soon.
